# Generated by Django 5.1.7 on 2025-07-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('township', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='employee_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=225, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=225, null=True)),
                ('ssb_id', models.CharField(blank=True, max_length=225, null=True)),
                ('nrc_no', models.CharField(max_length=225, unique=True)),
                ('fathername', models.CharField(max_length=225)),
                ('mothername', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('entrydate', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.TextField()),
                ('employee_status', models.IntegerField(default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('familytable', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('township', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.township')),
            ],
        ),
    ]
